# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /notes/:title.md

# Setup
title:            'Bagus18'
tagline:          'Bagus'
description:      'Limited by Imagination'
url:              'https://bagus18.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Bagus18'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/'
flickr:
github:         'https://github.com/bagus18'
gplus:          'https://plus.google.com/bagus18'
instagram:
pinterest:
linkedin:       'https://ae.linkedin.com/in/bagus18/'
rss:
stackoverflow:  'http://stackoverflow.com/bagus18'
twitter:        'https://twitter.com/bagus18'

# Google Analytics
gahandler: ''

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'bagus18'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
